# Generated by Django 4.2.7 on 2023-11-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='max_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='car',
            name='min_price',
        ),
        migrations.AlterField(
            model_name='car',
            name='marque',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='modele',
            field=models.CharField(max_length=100),
        ),
    ]
